// Mocks generated by Mockito 5.2.0 from annotations
// in flutter_wxcloudrun/test/client_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutter_wxcloudrun/src/client.dart' as _i3;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeClient_0 extends _i1.Fake implements _i2.Client {}

/// A class which mocks [WXCloudRunAPIClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockWXCloudRunAPIClient extends _i1.Mock
    implements _i3.WXCloudRunAPIClient {
  MockWXCloudRunAPIClient({required String apiRoot}) {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiRoot =>
      (super.noSuchMethod(Invocation.getter(#apiRoot), returnValue: '')
          as String);
  @override
  set apiRoot(String? _apiRoot) =>
      super.noSuchMethod(Invocation.setter(#apiRoot, _apiRoot),
          returnValueForMissingStub: null);
  @override
  String get format =>
      (super.noSuchMethod(Invocation.getter(#format), returnValue: '')
          as String);
  @override
  set format(String? _format) =>
      super.noSuchMethod(Invocation.setter(#format, _format),
          returnValueForMissingStub: null);
  @override
  bool get raw =>
      (super.noSuchMethod(Invocation.getter(#raw), returnValue: false) as bool);
  @override
  set raw(bool? _raw) => super.noSuchMethod(Invocation.setter(#raw, _raw),
      returnValueForMissingStub: null);
  @override
  _i2.Client get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeClient_0()) as _i2.Client);
  @override
  set client(_i2.Client? _client) =>
      super.noSuchMethod(Invocation.setter(#client, _client),
          returnValueForMissingStub: null);
  @override
  _i4.Future<dynamic> requestAPI(String? method, String? apiPath,
          {Map<String, dynamic>? queryParameters}) =>
      (super.noSuchMethod(
          Invocation.method(#requestAPI, [method, apiPath],
              {#queryParameters: queryParameters}),
          returnValue: Future<dynamic>.value()) as _i4.Future<dynamic>);
  @override
  dynamic parseResponse(_i2.Response? response) =>
      super.noSuchMethod(Invocation.method(#parseResponse, [response]));
}
